package com.example.tec.ui.theme

import androidx.compose.ui.graphics.Color

// Main light colors
val primaryLight = Color(0xFF304C95)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF5771BD)
val onPrimaryContainerLight = Color(0xFFFFFFFF)

val secondaryLight = Color(0xFF545D7C)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD6DEFF)
val onSecondaryContainerLight = Color(0xFF3C4562)

val tertiaryLight = Color(0xFF1A2462)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF3D4786)
val onTertiaryContainerLight = Color(0xFFE7E8FF)

val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)

val backgroundLight = Color(0xFFFAF8FF)
val onBackgroundLight = Color(0xFF1A1B20)

val surfaceLight = Color(0xFFFAF8FF)
val onSurfaceLight = Color(0xFF1A1B20)
val surfaceVariantLight = Color(0xFFE1E2EF)
val onSurfaceVariantLight = Color(0xFF444651)

val outlineLight = Color(0xFF757682)
val outlineVariantLight = Color(0xFFC4C6D2)

val scrimLight = Color(0xFF000000)

val inverseSurfaceLight = Color(0xFF2F3035)
val inverseOnSurfaceLight = Color(0xFFF1F0F7)
val inversePrimaryLight = Color(0xFFB4C5FF)

val surfaceDimLight = Color(0xFFDAD9E0)
val surfaceBrightLight = Color(0xFFFAF8FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF4F3FA)
val surfaceContainerLight = Color(0xFFEEEDF4)
val surfaceContainerHighLight = Color(0xFFE9E7EE)
val surfaceContainerHighestLight = Color(0xFFE3E2E9)
// ... till here.

val primaryLightMediumContrast = Color(0xFF213E87)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF5771BD)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF39425F)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF6A7493)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF1A2462)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF3D4786)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF8C0009)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFDA342E)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFAF8FF)
val onBackgroundLightMediumContrast = Color(0xFF1A1B20)
val surfaceLightMediumContrast = Color(0xFFFAF8FF)
val onSurfaceLightMediumContrast = Color(0xFF1A1B20)
val surfaceVariantLightMediumContrast = Color(0xFFE1E2EF)
val onSurfaceVariantLightMediumContrast = Color(0xFF40424D)
val outlineLightMediumContrast = Color(0xFF5C5F6A)
val outlineVariantLightMediumContrast = Color(0xFF787A86)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2F3035)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF1F0F7)
val inversePrimaryLightMediumContrast = Color(0xFFB4C5FF)
val surfaceDimLightMediumContrast = Color(0xFFDAD9E0)
val surfaceBrightLightMediumContrast = Color(0xFFFAF8FF)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF4F3FA)
val surfaceContainerLightMediumContrast = Color(0xFFEEEDF4)
val surfaceContainerHighLightMediumContrast = Color(0xFFE9E7EE)
val surfaceContainerHighestLightMediumContrast = Color(0xFFE3E2E9)

val primaryLightHighContrast = Color(0xFF001D59)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF213E87)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF18213C)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF39425F)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF101B59)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF343E7C)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF4E0002)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF8C0009)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFAF8FF)
val onBackgroundLightHighContrast = Color(0xFF1A1B20)
val surfaceLightHighContrast = Color(0xFFFAF8FF)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFE1E2EF)
val onSurfaceVariantLightHighContrast = Color(0xFF21242D)
val outlineLightHighContrast = Color(0xFF40424D)
val outlineVariantLightHighContrast = Color(0xFF40424D)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF2F3035)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFE8EBFF)
val surfaceDimLightHighContrast = Color(0xFFDAD9E0)
val surfaceBrightLightHighContrast = Color(0xFFFAF8FF)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF4F3FA)
val surfaceContainerLightHighContrast = Color(0xFFEEEDF4)
val surfaceContainerHighLightHighContrast = Color(0xFFE9E7EE)
val surfaceContainerHighestLightHighContrast = Color(0xFFE3E2E9)

// Main dark colors
val primaryDark = Color(0xFFB4C5FF)
val onPrimaryDark = Color(0xFF052B74)
val primaryContainerDark = Color(0xFF5771BD)
val onPrimaryContainerDark = Color(0xFFFFFFFF)

val secondaryDark = Color(0xFFBCC5E9)
val onSecondaryDark = Color(0xFF262F4B)
val secondaryContainerDark = Color(0xFF363F5C)
val onSecondaryContainerDark = Color(0xFFCAD3F7)

val tertiaryDark = Color(0xFFBBC3FF)
val onTertiaryDark = Color(0xFF202A68)
val tertiaryContainerDark = Color(0xFF242E6C)
val onTertiaryContainerDark = Color(0xFFB7C0FF)

val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)

val backgroundDark = Color(0xFF121318)
val onBackgroundDark = Color(0xFFE3E2E9)

val surfaceDark = Color(0xFF121318)
val onSurfaceDark = Color(0xFFE3E2E9)
val surfaceVariantDark = Color(0xFF444651)
val onSurfaceVariantDark = Color(0xFFC4C6D2)

val outlineDark = Color(0xFF8E909C)
val outlineVariantDark = Color(0xFF444651)

val scrimDark = Color(0xFF000000)

val inverseSurfaceDark = Color(0xFFE3E2E9)
val inverseOnSurfaceDark = Color(0xFF2F3035)
val inversePrimaryDark = Color(0xFF405BA5)

val surfaceDimDark = Color(0xFF121318)
val surfaceBrightDark = Color(0xFF38393E)
val surfaceContainerLowestDark = Color(0xFF0D0E13)
val surfaceContainerLowDark = Color(0xFF1A1B20)
val surfaceContainerDark = Color(0xFF1E1F24)
val surfaceContainerHighDark = Color(0xFF292A2F)
val surfaceContainerHighestDark = Color(0xFF34343A)
// ... till here

val primaryDarkMediumContrast = Color(0xFFBAC9FF)
val onPrimaryDarkMediumContrast = Color(0xFF00133F)
val primaryContainerDarkMediumContrast = Color(0xFF748EDC)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFC1CAED)
val onSecondaryDarkMediumContrast = Color(0xFF0B1530)
val secondaryContainerDarkMediumContrast = Color(0xFF8790B1)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFC0C7FF)
val onTertiaryDarkMediumContrast = Color(0xFF010C4E)
val tertiaryContainerDarkMediumContrast = Color(0xFF828CD0)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFBAB1)
val onErrorDarkMediumContrast = Color(0xFF370001)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF121318)
val onBackgroundDarkMediumContrast = Color(0xFFE3E2E9)
val surfaceDarkMediumContrast = Color(0xFF121318)
val onSurfaceDarkMediumContrast = Color(0xFFFCFAFF)
val surfaceVariantDarkMediumContrast = Color(0xFF444651)
val onSurfaceVariantDarkMediumContrast = Color(0xFFC9CAD7)
val outlineDarkMediumContrast = Color(0xFFA1A2AE)
val outlineVariantDarkMediumContrast = Color(0xFF81828E)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE3E2E9)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF292A2F)
val inversePrimaryDarkMediumContrast = Color(0xFF27448D)
val surfaceDimDarkMediumContrast = Color(0xFF121318)
val surfaceBrightDarkMediumContrast = Color(0xFF38393E)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF0D0E13)
val surfaceContainerLowDarkMediumContrast = Color(0xFF1A1B20)
val surfaceContainerDarkMediumContrast = Color(0xFF1E1F24)
val surfaceContainerHighDarkMediumContrast = Color(0xFF292A2F)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF34343A)

val primaryDarkHighContrast = Color(0xFFFCFAFF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFBAC9FF)
val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
val secondaryDarkHighContrast = Color(0xFFFCFAFF)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFC1CAED)
val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
val tertiaryDarkHighContrast = Color(0xFFFDFAFF)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFC0C7FF)
val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
val errorDarkHighContrast = Color(0xFFFFF9F9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFBAB1)
val onErrorContainerDarkHighContrast = Color(0xFF000000)
val backgroundDarkHighContrast = Color(0xFF121318)
val onBackgroundDarkHighContrast = Color(0xFFE3E2E9)
val surfaceDarkHighContrast = Color(0xFF121318)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF444651)
val onSurfaceVariantDarkHighContrast = Color(0xFFFCFAFF)
val outlineDarkHighContrast = Color(0xFFC9CAD7)
val outlineVariantDarkHighContrast = Color(0xFFC9CAD7)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE3E2E9)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF002469)
val surfaceDimDarkHighContrast = Color(0xFF121318)
val surfaceBrightDarkHighContrast = Color(0xFF38393E)
val surfaceContainerLowestDarkHighContrast = Color(0xFF0D0E13)
val surfaceContainerLowDarkHighContrast = Color(0xFF1A1B20)
val surfaceContainerDarkHighContrast = Color(0xFF1E1F24)
val surfaceContainerHighDarkHighContrast = Color(0xFF292A2F)
val surfaceContainerHighestDarkHighContrast = Color(0xFF34343A)